enh: tf_masking1  # enhanced relation
enh_conf:
    loss_type: magnitude3 
    n_fft: 512
    hop_length: 256
    rnn_type: blstm
    layer: 3
    unit: 896
    dropout: 0.5
    num_spk: 1
    mvn_dict: "./cmvn_center_true3.dst" 
    nonlinear: mish

# ASR related
# network architecture
frontend: default # asr frontend relation 
frontend_conf:
   fs: 8000
   n_fft: 512
   n_mels: 80
   fmin: 0
   fmax: 4000
   htk: False
   #log_base: None

specaug: None
#normalize: "global_mvn" 

# encoder related
encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true
    concat_after: false
    positionwise_layer_type: linear
    macaron_style: true
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 15

# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

#asr   hybrid enh/CTC/attention
# loss 
asr_model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1     # label smoothing option
    enh_weight: 0.3
    clean_weight: 0.7     # mix speech branch weight 
    num_channels: 64
    num_iff_blocks: 4
    style_weight: 0.01    
    cons_weight: 0.4
    length_normalized_loss: false

unused_parameters: true

# minibatch related
batch_type: folded
batch_size: 64
accum_grad: 1
num_att_plot: 0
# optimization related
grad_clip: 5
patience: 50
max_epoch: 50
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.002
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 25000
